---
title: "Particle_Tracker"
author: "MChas Sumner"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)
library(imager)
library(tidyverse)
library(stats)
library(data.table)
library(boot)

knitr::opts_chunk$set(echo = TRUE)

twopos.pythag <- function(a, b) {
  sqrt((a[1] - b[1])^2 + (a[2] - b[2])^2)
}

```


```{r Main_Func}


Track.Foci <- function(nd_file_name = ".nd", 
                       nd_dir = ".",
                       image_file_type = ".TIF"){
  
  setwd(nd_dir)
  
  nd_fnames <- list.files(pattern = nd_file_name)[1]
  
  foci_fnames <- list.files(pattern = image_file_type)
  
  foci_fnames <- foci_fnames[str_detect(foci_fnames,"Yoko Green")]
  
  for(i in 1:length(nd_fnames)){
    
    curr_nd_identity <- str_split(nd_fnames[i], 
                                  pattern = "\\.")[[1]][1]
    
    return(Thresh.Track(curr_nd_identity, 
                       secondary_threshold = "95%"))
    
  }
  
}

```



```{r Threshold_Tracker}

  Thresh.Track <- function(image_files_name_pattern, 
               primary_threshold = "99%", 
               secondary_threshold = NA,
               time_interval = 0.21,
               pixel_width = 0.0881,
               prev_thresh = 0.35){
    
    file_vec <- list.files(pattern = image_files_name_pattern)
    
    file_vec <- file_vec[str_detect(file_vec, ".TIF")]
    
    file_vec <- file_vec[str_detect(file_vec, "Green")]
    
    len_file_vec <- length(file_vec)
    
    #initiate loop objects and structures
    skipped_step <- FALSE
    
    foci_positions <- matrix(0, nrow =len_file_vec, ncol = 4)
    
    foci_positions[,3] <- seq(0,(nrow(foci_positions)-1)*0.21,0.21)
    
    for(i in 1:len_file_vec){
      
      curr_image_name <- paste(image_files_name_pattern, 
                               "_w106 Yoko Green_t",
                               i,
                               ".TIF",
                               sep="")
      
      curr_image_raw <- load.image(curr_image_name)
      
      #first pass with desired threshold
      curr_image_thresh <- curr_image_raw %>%
        threshold(primary_threshold) %>%
        clean(2)
      
      foci_pix <- which(curr_image_thresh)
      
      if(length(foci_pix) < 3) {
      
        if(!is.na(secondary_threshold)){
        
          #if foci not found, try with a second threshold, if supplied
          curr_image_thresh <- curr_image_raw %>%
          threshold(secondary_threshold) %>%
          clean(2)
        
          foci_pix <- which(curr_image_thresh)
          
        }
        
        #note if foci not found, skip
        if(length(foci_pix) < 1){
          
          print("Lost step")
          
          skipped_step = TRUE
          
          next
          
        }
        
      }
      
      #The FUN part of working with pixel sets, putting pixels in place
      width_curr_image <- (dim(curr_image_thresh))[1]

      foci_mat <- matrix(0, length(foci_pix), ncol = 3)

      foci_mat[, 1] <- foci_pix %% width_curr_image

      foci_mat[, 2] <- 1 + (foci_pix %/% width_curr_image)

      foci_mat[, 3] <- curr_image_raw[foci_pix]

      foci_pos <- c(weighted.mean(foci_mat[, 1],
                                  foci_mat[, 3]), 
                    weighted.mean(foci_mat[, 2], 
                                  foci_mat[, 3]))
      
      adj_foci_pos <- foci_pos * pixel_width
      
      if(i > 1){
        
        if(skipped_step){
          
          foci_positions[i-1,c(1,2)] <- c(mean(adj_foci_pos[1],
                                               foci_positions[i-2,1]),
                                          mean(adj_foci_pos[2],
                                               foci_positions[i-2,2]))
          
          asm_dist_2_prev <- twopos.pythag(foci_positions[i-1,c(1,2)],
                                                 foci_positions[i-2,c(1,2)])
          
          if(asm_dist_2_prev > prev_thresh){
            
            print("Sequential Lost")
            
            stop(paste("FOR: ", curr_image_name))
            
          }
          
          foci_positions[i-1,4] <- twopos.pythag(foci_positions[i-1,c(1,2)],
                                                 foci_positions[i-2,c(1,2)])
          
        }
        
        dist_2_prev <- twopos.pythag(adj_foci_pos,
                                     foci_positions[i-1,c(1,2)])
        
        if(dist_2_prev > prev_thresh){
          
          if(!skipped_step){
            
            skipped_step <- TRUE
            
          }else{
            
            stop(paste("TOO LARGE ONE STEP FOR: ", image_names[i]))
            
          }
          
          next
          
        }
        
              foci_positions[i,4] <- dist_2_prev
        
      }
      
      foci_positions[i,c(1,2)] <- adj_foci_pos
        
      skipped_step <- FALSE
      
    }
    
    fp_df <- as.data.frame(foci_positions)
    
    colnames(fp_df) <- c("x_pos","y_pos","time","d2prev")
    
    return(fp_df)
    
  }




```


