---
title: "Analysis for Trajectories"
author: "Michael Chas Sumner"
output:
  html_document: default
params:
  list_source_wd_pos: 26
  time_interval: 0.21
  expected_nrow: 2000
  
---


```{r setup, echo=F,include = F}
library(stats)

library(data.table)

library(tidyverse)

library(gganimate)

library(gifski)

library(viridis)

library(knitr)

library(gridExtra)

source(paste(pull_dir, "Simulated_MSD.R", sep = ""), echo = FALSE)

source(paste(pull_dir, "smoothMSD.R", sep = ""), echo = FALSE)

source(paste(pull_dir, "SimLin_Repos.R", sep = ""), echo = FALSE)

source(paste(pull_dir, "multimsd.R", sep = ""), echo = FALSE)

source(paste(pull_dir, "SimClustFuncs.R", sep = ""), echo = FALSE)

# pulled_git_directory

pull_dir <- "~/PULLS/R_sim_scripts/"

# Your dataset directory
dataset_dir <- "~/DataSets/"

file_dir <- paste(dataset_dir, "/mrkdwn_active_datasets/", sep = "")

# set this to the raw_data directory
root_dir <- file_dir

opts_knit$set(root.dir = root_dir)


uap <- "U3alonePlus"
gup <- "G1atU3Plus"

comtheme <- theme_bw() +
  theme(
    text = element_text(color = "#545454", size = 18),
    legend.position = "none"
  )
```




## chunk1, create list of trajectories as matrices


```{r sim_list_chunk, echo=F, warning=F}



# Parameters that matter!
# How many rows (positions) do you expect?
expected_nrow <- params$expected_nrow
# What is the interval of time between positions?
time_interval <- params$time_interval

# Do you want to remove trajectories that are not the expected length or contain
# either NAs or NaNs?
remove_incomplete_trajectoreies <- T

# specify the directory containing trajectory .csv files
list_source_wd <- list.files()[params$list_source_wd_pos]

print(paste("trajectories used: ", list_source_wd, sep = ""))
setwd(list_source_wd)

list_source_wd <- getwd() %>%
  strsplit("/") %>%
  unlist()
list_source_wd <- list_source_wd[length(list_source_wd)]

sim_list <- vector(mode = "list", length = length(list.files()))

for (i in 1:length(list.files())) {
  if (i == 1) {
    sim_list <- vector(mode = "list", length = length(list.files()))
  }

  sim_list[[i]] <- as.matrix(fread(list.files()[i]))
}

if (remove_incomplete_trajectoreies == T) {
  cleaned_list <- list()
  clean_position <- 0

  for (i in 1:length(sim_list)) {
    tail_check <- sim_list[[i]][nrow(sim_list[[i]]), ]

    if (NA %in% sim_list[[i]] | NaN %in% sim_list[[i]] | nrow(sim_list[[i]]) < expected_nrow) {
      print("NA NaN or Error detected")
      next
    } else {
      clean_position <- clean_position + 1

      cleaned_list[[clean_position]] <- sim_list[[i]]
    }
  }
  print(paste(length(cleaned_list), "/", length(sim_list), " trajectories used.", sep = ""))
  sim_list <- cleaned_list
}

start_x <- c()
start_y <- c()

for (i in 1:length(sim_list)) {
  start_x <- c(start_x, sim_list[[i]][1, 1])
  start_y <- c(start_y, sim_list[[i]][1, 2])
}

start_frame <- data.frame(
  ID = seq(1, length(start_x), 1), x = start_x,
  y = start_y, rad = sqrt(start_x^2 + start_y^2)
)

shist_plot <- ggplot(data = start_frame) +
  geom_freqpoly(aes(x = rad), bins = 10) +
  comtheme +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Start Position Radii")

spos_plot <- ggplot(data = start_frame) +
  geom_point(aes(x = x, y = y)) +
  comtheme +
  coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1)) +
  labs(title = "Start Positions")

sx_plot <- ggplot(data = start_frame) +
  geom_freqpoly(aes(x = x), bins = 10) +
  comtheme +
  labs(title = "Start X")

sy_plot <- ggplot(data = start_frame) +
  geom_freqpoly(aes(x = y), bins = 10) +
  comtheme +
  labs(title = "Start Y")

end_x <- c()
end_y <- c()

for (i in 1:length(sim_list)) {
  end_x <- c(end_x, sim_list[[i]][nrow(sim_list[[i]]), 1])
  end_y <- c(end_y, sim_list[[i]][nrow(sim_list[[i]]), 2])
}

end_frame <- data.frame(ID = seq(1, length(end_x), 1), x = end_x, y = end_y, rad = sqrt(end_x^2 + end_y^2))

ehist_plot <- ggplot(data = end_frame) +
  geom_freqpoly(aes(x = rad), bins = 10) +
  comtheme +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "End Position Radii")

epos_plot <- ggplot(data = end_frame) +
  geom_point(aes(x = x, y = y)) +
  comtheme +
  coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1)) +
  labs(title = "End Positions")

ex_plot <- ggplot(data = end_frame) +
  geom_freqpoly(aes(x = x), bins = 10) +
  comtheme +
  labs(title = "End X")

ey_plot <- ggplot(data = end_frame) +
  geom_freqpoly(aes(x = y), bins = 10) +
  comtheme +
  labs(title = "End Y")

grid.arrange(shist_plot, spos_plot, ehist_plot, epos_plot)

grid.arrange(sx_plot, sy_plot, ex_plot, ey_plot)
```


```{r d2_list_chunk, message=FALSE, echo = F, include = F}

## Create a more robust data set with relative distances
# and ensure you have a plasubile d2o distribution


TBF <- sim_list
subTBF_nrow <- length(TBF[[1]][, 1])
time_seq <- matrix(seq(0, (subTBF_nrow - 1) * time_interval, time_interval), ncol = 1)
for (i in 1:length(TBF)) {
  TBF[[i]] <- cbind(TBF[[i]][, c(1, 2)], time_seq)
  colnames(TBF[[i]]) <- c("x", "y", "time")
}

t_int <- TBF[[1]][, "time"][2]
d2svec <- c(0)
d2pvec <- c(0)
d2ovec <- c(0)
tot_d2o <- c()
d2_list <- vector("list", length(TBF))

for (i in 1:length(TBF)) {
  float_mat <- TBF[[i]]
  d2ovec[1] <- sqrt(float_mat[1, 1]^2 + float_mat[1, 2]^2)
  for (j in 2:nrow(float_mat)) {
    d2svec[j] <-
      sqrt((float_mat[1, 1] - float_mat[j, 1])^2 + (float_mat[1, 2] - float_mat[j, 2])^
        2)
    d2p_x <- float_mat[(j - 1), 1] - float_mat[j, 1]
    d2p_y <- float_mat[(j - 1), 2] - float_mat[j, 2]
    d2pvec[j] <- sqrt(d2p_x^2 + d2p_y^2)
    d2ovec[j] <- sqrt(float_mat[j, 1]^2 + float_mat[j, 2]^2)
    if(d2pvec[j] >= 0.5) print(d2pvec[j])
  }
  float_mat <-
    cbind(
      float_mat,
      matrix(d2svec, ncol = 1),
      matrix(d2pvec, ncol = 1),
      matrix(d2ovec, ncol = 1)
    )
  colnames(float_mat) <-
    c("x", "y", "time", "D2S", "D2P", "D2O")
  row.names(float_mat) <- c(1:nrow(float_mat))
  d2_list[[i]] <- float_mat
  tot_d2o <- c(tot_d2o, d2ovec)
}

plot(density(tot_d2o, from = 0, to = max(tot_d2o)))

```




## Visualize Peripheral Occupancy

```{r peripheral_occupancy, echo=F, warning=F}

print_plots <- TRUE

periph_occu_list <- vector("list", length(d2_list))

# Use debuff feature if you want to ONLY look at equilibrium at end of trajectories
Peri_Debuff <- F
Debuff_Output_Length <- as.integer(600 / time_interval)

bound_zone_thickness <- 0.15 #microns
  #(1 - sqrt(2 / 3)) # this is outer third of nucleus with radius = 1 micron

if (Peri_Debuff) {
  # pre_allocate new po_list
  po_list <- lapply(1:length(d2_list), matrix, data = NA, nrow = Debuff_Output_Length, ncol = ncol(d2_list[[1]]))
  for (i in 1:length(d2_list)) {
    nrow_d2l <- nrow(d2_list[[i]])
    po_list[[i]] <- d2_list[[i]][((nrow_d2l - Debuff_Output_Length):nrow_d2l), ]
  }
} else {
  po_list <- d2_list
}

for (i in 1:length(po_list)) {
  float_po_logic <- po_list[[i]][, "D2O"] > (1 - bound_zone_thickness)
  float_po_matrix <-
    matrix(seq(0, (length(float_po_logic) - 1) * time_interval, time_interval), ncol = 1)
  periph_occu_list[[i]] <-
    cbind(float_po_matrix, matrix(as.numeric(float_po_logic), ncol = 1))
}

preproc_NAs <-

  rep(NA, (length(periph_occu_list[[i]][, 1]) * length(periph_occu_list)))
po_plot_frame <-
  data.frame(
    Trajectory = preproc_NAs,
    time = preproc_NAs,
    is_periph = preproc_NAs
  )

for (i in 1:length(periph_occu_list)) {
  po_plot_frame[((i - 1) * nrow(periph_occu_list[[i]]) + 1):(i * nrow(periph_occu_list[[i]])), ] <-
    data.frame(
      Trajectory = i,
      time = periph_occu_list[[i]][, 1],
      is_periph = periph_occu_list[[i]][, 2]
    )
}

time_nrow <- length(unique(po_plot_frame$time))

float_time_interval <- po_plot_frame$time[2] - po_plot_frame$time[1]

mpp_frame <- po_plot_frame[po_plot_frame$time <= (float_time_interval * time_nrow), ]

order_mat <- matrix(nrow = length(unique(mpp_frame$Trajectory)), ncol = 2)

for (i in 1:length(unique(mpp_frame$Trajectory))) {
  float_pot <- mean(mpp_frame[mpp_frame$Trajectory == (unique(mpp_frame$Trajectory)[i]), "is_periph"])
  order_mat[i, ] <- c(i, float_pot)
}

new_order <- order(order_mat[, 2])

nompp_frame <- mutate(mpp_frame, rank = NA)

for (i in 1:length(unique(mpp_frame$Trajectory))) {
  temp_traj <- mpp_frame[mpp_frame$Trajectory == new_order[i], ]
  nompp_frame[(((i - 1) * nrow(temp_traj)) + 1):(i * nrow(temp_traj)), -(ncol(nompp_frame))] <- temp_traj
  nompp_frame[(((i - 1) * nrow(temp_traj)) + 1):(i * nrow(temp_traj)), (ncol(nompp_frame))] <- i
}

po_plot <- ggplot(data = nompp_frame) +
  geom_tile(aes(
    x = time,
    y = Trajectory,
    color = is_periph,
    fill = is_periph
  ),
  position = "dodge"
  ) +
  scale_colour_viridis() +
  scale_fill_viridis() +
  coord_cartesian(xlim = c(0, (float_time_interval * time_nrow))) +
  comtheme +
  ylab("Simulated Trajectory with Zipcode") +
  xlab("time (s)")


po_avg_time_frame <- data.frame(time = rep(NA, time_nrow), bound_frac = rep(NA, time_nrow))

for (i in 1:time_nrow) {
  cur_time <- float_time_interval * (i - 1)
  po_avg_time_frame[i, 1] <- cur_time
  po_avg_time_frame[i, 2] <- mean(mpp_frame[mpp_frame$time == cur_time, ]$is_periph)
}

pat_plot <- ggplot(data = po_avg_time_frame) +
  geom_point(aes(x = time, y = bound_frac * 100), alpha = 0.1) +
  stat_smooth(aes(x = time, y = bound_frac * 100)) +
  coord_cartesian(ylim = c(0, 100)) +
  comtheme +
  ylab("% of Trajectories at the periphery") +
  xlab("time (s)")

traj_vec <- unique(nompp_frame$Trajectory)

# TODO: Preallocate when not lazy
vpat_frame <- data.frame(ID = numeric(), peri_perc = numeric())

for (i in 1:length(unique(nompp_frame$Trajectory))) {
  float_traj <- traj_vec[i]
  float_frame <- nompp_frame[nompp_frame$Trajectory == float_traj, ]
  vpat_frame[i, 1] <- float_traj
  vpat_frame[i, 2] <- sum(float_frame$is_periph) / nrow(float_frame)
}

vpat_plot <- ggplot(data = vpat_frame) +
  coord_cartesian(ylim = c(0, 100)) +
  geom_violin(aes(y = peri_perc * 100, x = "SIM"), fill = "yellow") +
  geom_errorbar(aes(ymax = mean(peri_perc) * 100 + sd(peri_perc) * 100, ymin = mean(peri_perc) * 100 - sd(peri_perc) * 100, x = "SIM"), width = 0.5) +
  geom_point(aes(y = mean(peri_perc) * 100, x = "SIM"), color = "white", size = 4, shape = 19) +
  ylab("peripheral (% of time)") +
  comtheme

if (print_plots) {
  print(po_plot)
  # print(vpat_plot)
  print(pat_plot)
}
```


```{r MSD, eval=T, include=F}

msd_dir <- "~/DataSets/trajectory_r_data/analytical_environment/calculated_MSD"
merge_dir <- "~/DataSets/trajectory_r_data/analytical_environment/MSD_merged"


for (i in 1:length(d2_list)) {
  if (i == 1) {
    msd_list <- vector(mode = "list", length = length(d2_list))
  }
  sl_len <- nrow(d2_list[[i]])
  msd_list[[i]] <- d2_list[[i]][((sl_len - 199):sl_len), ]
}

print(list_source_wd)
simMSD(msd_list, list_source_wd, output_dir = msd_dir)
kurzplot(list_source_wd, msd_input_dir = msd_dir, merge_output_dir = merge_dir)
```

```{r multimsd, eval=FALSE, message=FALSE, include=FALSE}

mmsdplot(c("FLE_URA3", "Uniform_Steps", "Gaussian_Steps"))
```

```{r Repositioning, eval = FALSE}
source(paste(pull_dir, "SimLin_Repos.R", sep = ""), echo = FALSE)

Repos_List <- d2_list
sim_lin()

tvv_frame <- data.frame(velocity = tvv)

velo_plot <- ggplot(data = tvv_frame) +
  geom_freqpoly(aes(x = velocity), bins = 30) +
  comtheme

time_plot <- ggplot(data = global_summary_sim) +
  geom_density(aes(x = time)) +
  coord_cartesian(xlim = c(0, max(global_summary_sim$time))) +
  comtheme

mdt_plot <- ggplot(data = global_summary_sim) +
  geom_density(aes(x = mean_delta_theta)) +
  comtheme

mdd_plot <- ggplot(data = global_direct_sim) +
  geom_freqpoly(aes(x = delta_dist), bins = 30) +
  comtheme

grid.arrange(velo_plot, time_plot, mdt_plot, mdd_plot)
```


```{r Clusters, echo=F, eval = F}
# randomize the d2_list into two pairwise lists

source(paste(pull_dir, "SimClustFuncs.R", sep = ""), echo = FALSE)

set.seed(57343)

d2_list_length <- length(d2_list)

last_200_list <- vector(mode = "list", length = d2_list_length)

for (i in 1:d2_list_length) {
  sl_len <- length(d2_list[[i]][, 1])
  last_200_list[[i]] <- d2_list[[i]][((sl_len - 199):sl_len), ]
}

rand_d2 <- sample.int(d2_list_length)

pri_d2_IDs <- rand_d2[c(1:(d2_list_length / 2))]

sec_d2_IDs <- rand_d2[c((d2_list_length / 2 + 1):d2_list_length)]

plen <- length(pri_d2_IDs)

slen <- length(sec_d2_IDs)

if (plen != slen) stop("d2_list was split improperly or is odd")

# perform cluster component analysis on the two lists in a pairwise fashion

# initialize arg_lists

pri_list <- last_200_list[pri_d2_IDs]
sec_list <- last_200_list[sec_d2_IDs]

pri_xy_list <- lapply(1:plen, matrix, data = NA, ncol = 2, nrow = nrow(pri_list[[1]]))
sec_xy_list <- lapply(1:slen, matrix, data = NA, ncol = 2, nrow = nrow(sec_list[[1]]))


for (i in 1:plen) {
  pri_xy_list[[i]] <- pri_list[[i]][, c("x", "y")]
  sec_xy_list[[i]] <- sec_list[[i]][, c("x", "y")]
}



id_matlist <- sim_clust_interdist(pri_xy_list, sec_xy_list)

mean_id_mat <- matrix(data = NA, nrow = length(id_matlist), ncol = 2)

for (i in 1:length(id_matlist)) {
  mean_id_mat[i, ] <- c(i, mean(id_matlist[[i]][, 1]))
}

mean_id_frame <- as.data.frame(mean_id_mat)

colnames(mean_id_frame) <- c("Pair_ID", "interdist")

interdist_plot <- ggplot(data = mean_id_frame, aes(x = "Sim", y = interdist)) +
  geom_jitter(color = "blue", height = 0, width = 0.1) +
  coord_cartesian(ylim = c(0, 2)) +
  geom_boxplot(width = 0.1, notch = T) +
  comtheme

magcor_frame <- sim_clust_magcor(pri_xy_list, sec_xy_list)

magcor_plot <- ggplot(data = magcor_frame, aes(x = "Sim", y = mag_PCC)) +
  geom_jitter(color = "red", height = 0, width = 0.1) +
  coord_cartesian(ylim = c(-1, 1)) +
  geom_boxplot(width = 0.1, notch = T) +
  comtheme

clust_theta_list <- sim_clust_theta(pri_xy_list, sec_xy_list)

ctl_len <- length(clust_theta_list)

mean_clust_theta_frame <- data.frame(Pair_ID = numeric(), mean_theta = numeric())

for (i in 1:ctl_len) {
  mean_clust_theta_frame[i, ] <- c(i, mean(clust_theta_list[[i]], na.rm = T))
}

theta_plot <- ggplot(data = mean_clust_theta_frame, aes(x = "Sim", y = mean_theta)) +
  geom_jitter(color = "purple", height = 0, width = 0.1) +
  geom_boxplot(width = 0.1, notch = T) +
  coord_cartesian(ylim = c(0, 3.14)) +
  comtheme

sim_clust_comp_frame <- cbind(magcor_frame, mean_clust_theta_frame[, 2], mean_id_frame[, 2])

colnames(sim_clust_comp_frame) <- c("exp", "dCorr", "Delta_Theta", "avg_Dist")

# time and fraction of total trajectory time spent clustered

life_frac_list <- sim_clust_lifefrac(id_matlist, time_interval)

life_frame <- as.data.frame(life_frac_list[[1]]) %>%
  mutate(ID = list_source_wd) %>%
  mutate(ID_num = 20)
colnames(life_frame) <- c("lifefrac", "exp", "ID", "ID_num")

life_plot <- ggplot(data = life_frame, aes(x = "Sim", y = lifefrac)) +
  geom_jitter(color = "green", height = 0, width = 0.1) +
  geom_boxplot(width = 0.1, notch = F) +
  coord_cartesian(ylim = c(0, 1)) +
  comtheme

# create ouput frame


output_cluster_comp <- data.frame(ID = list_source_wd, exp = mean_id_frame[, "Pair_ID"], dCorr = magcor_frame[, "mag_PCC"], Delta_Theta = mean_clust_theta_frame[, "mean_theta"], avg_Dist = mean_id_frame[, "interdist"])




grid.arrange(interdist_plot, magcor_plot, theta_plot, life_plot)
```


```{r Animate, echo=F}
# dependent on d2_list

save_product <- F

fname <- list_source_wd

d2len <- length(d2_list)
# d2len <- 10
d2nrow <- nrow(d2_list[[1]])
d2ncol <- ncol(d2_list[[1]])

big_float_mat <- matrix(ncol = d2ncol + 1, nrow = d2nrow * d2len)

for (i in 1:d2len) {
  big_float_mat[((i - 1) * d2nrow + 1):(i * d2nrow), -(d2ncol + 1)] <- d2_list[[i]][1:d2nrow, 1:d2ncol]
  big_float_mat[((i - 1) * d2nrow + 1):(i * d2nrow), d2ncol + 1] <-
    rep(i, d2nrow)
}

float_frame <- as.data.frame(big_float_mat)

colnames(float_frame) <- c(colnames(d2_list[[1]]), "ID")

big_pos_frame <- data.frame(x_pos = as.numeric(rep(NA, d2nrow * d2len)), y_pos = as.numeric(rep(NA, d2nrow * d2len)), time = as.numeric(rep(NA, d2nrow * d2len)), ID = as.character(rep(NA, d2nrow * d2len)))

for (i in 1:d2len) {
  float_df <- as.data.frame(d2_list[[i]][, c("x", "y", "time")])
  float_df[, 4] <- i
  big_pos_frame[((i - 1) * d2nrow + 1):(i * d2nrow), 1:4] <- float_df
}

max_plot <- ggplot(data = big_pos_frame, aes(x = x_pos, y = y_pos)) +
  geom_bin2d(bins = 50)+
  scale_fill_gradient(low = "white", high = "red") +
  comtheme +
  #theme(legend.position = "right") +
  xlab("") +
  ylab("")


print(max_plot)


# traj_anim <- ggplot(data = float_frame, aes(x = time, y = y, group = ID)) +
#   coord_cartesian(ylim = c(-1, 1)) +
#   geom_path(alpha = 0.25, size = 1) +
#   # geom_point(alpha = 0.5)+
#   comtheme +
#   scale_color_viridis(discrete = F) +
#   scale_fill_viridis(discrete = F) +
#   labs(x = "time (s)", y = "Simulated Y position (micron)") +
#   transition_reveal(time)

if (save_product) {
  animate(traj_anim, duration = 5, fps = 20, width = 1200, height = 600, renderer = gifski_renderer())
  anim_save(filename = paste(fname, ".gif", sep = ""), animaion = traj_anim, path = ".")
  # ggsave(paste(fname,".png",sep=""),width = 30, height = 15, units = "cm")
}
```
